default:
  interruptible: false
  image:
    name: registry.timmertech.nl/docker/docker:latest
    pull_policy: always

include:
  - project: templates/ci
    file: docker.yml

base:
  extends: .docker-build-multi
  stage: build
  only:
    - main
    - schedules
    - branches
  variables:
    PLATFORM: "linux/arm64,linux/amd64"
    DOCKER_FILE: docker/Dockerfile.base
    DOCKER_HUB: "ENABLED"
    DOCKER_IMAGE: ${DOCKER_IMAGE_PATH}:base
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:base

psql:9:
  extends: .docker-build-multi
  stage: build
  needs:
    - base
  only:
    - main
    - schedules
  variables:
    PLATFORM: "linux/arm64,linux/amd64"
    DOCKER_HUB: "ENABLED"
    DOCKER_FILE: docker/Dockerfile.psql.9
    DOCKER_IMAGE: ${DOCKER_IMAGE_PATH}:9
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:9

psql:10:
  extends: .docker-build-multi
  stage: build
  needs:
    - base
  only:
    - main
    - schedules
  variables:
    PLATFORM: "linux/arm64,linux/amd64"
    DOCKER_HUB: "ENABLED"
    DOCKER_FILE: docker/Dockerfile.psql.10
    DOCKER_IMAGE: ${DOCKER_IMAGE_PATH}:10
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:10

psql:11:
  extends: .docker-build-multi
  stage: build
  needs:
    - base
  only:
    - main
    - schedules
  variables:
    PLATFORM: "linux/arm64,linux/amd64"
    DOCKER_HUB: "ENABLED"
    DOCKER_FILE: docker/Dockerfile.psql.11
    DOCKER_IMAGE: ${DOCKER_IMAGE_PATH}:11
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:11

psql:12:
  extends: .docker-build-multi
  stage: build
  needs:
    - base
  only:
    - main
    - schedules
  variables:
    PLATFORM: "linux/arm64,linux/amd64"
    DOCKER_HUB: "ENABLED"
    DOCKER_FILE: docker/Dockerfile.psql.12
    DOCKER_IMAGE: ${DOCKER_IMAGE_PATH}:12
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:12
    BUILD_ARGS: >-
      -build-arg=PG_COMMAND=/usr/bin/postgres12

psql:13:
  extends: .docker-build-multi
  stage: build
  needs:
    - base
  only:
    - main
    - schedules
  variables:
    PLATFORM: "linux/arm64,linux/amd64"
    DOCKER_HUB: "ENABLED"
    DOCKER_FILE: docker/Dockerfile.psql.13
    DOCKER_IMAGE: ${DOCKER_IMAGE_PATH}:13
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:13
    BUILD_ARGS: >-
      -build-arg=PG_COMMAND=/usr/bin/postgres13

psql:14:
  extends: .docker-build-multi
  stage: build
  needs:
    - base
  only:
    - main
    - schedules
  variables:
    PLATFORM: "linux/arm64,linux/amd64"
    DOCKER_HUB: "ENABLED"
    DOCKER_FILE: docker/Dockerfile.psql.14
    DOCKER_IMAGE: ${DOCKER_IMAGE_PATH}:14
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:14
    BUILD_ARGS: >-
      -build-arg=PG_COMMAND=/usr/bin/postgres14

psql:15:
  extends: .docker-build-multi
  stage: build
  needs:
    - base
  only:
    - main
    - schedules
  variables:
    PLATFORM: "linux/arm64,linux/amd64"
    DOCKER_HUB: "ENABLED"
    DOCKER_FILE: docker/Dockerfile.psql.15
    DOCKER_IMAGE: ${DOCKER_IMAGE_PATH}:15
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_PATH}:latest
      --tag=${DOCKER_IMAGE_HUB_PATH}:15
      --tag=${DOCKER_IMAGE_HUB_PATH}:latest
    BUILD_ARGS: >-
      -build-arg=PG_COMMAND=/usr/bin/postgres15

dockerhub:description:
  stage: deploy
  image: peterevans/dockerhub-description:3
  variables:
    DOCKERHUB_USERNAME: $DOCKER_HUB_USER
    DOCKERHUB_PASSWORD: $DOCKER_HUB_PASS
    DOCKERHUB_REPOSITORY: ${DOCKER_HUB_NAMESPACE}/${CI_PROJECT_NAME}
    README_FILEPATH: $CI_PROJECT_DIR/README.md
  only:
    - main
    - schedules
  script:
    - echo "Uploading Description"
