image: registry.timmertech.nl/docker/docker:latest

stages:
  - build
  - latest
  - dockerhub

include:
  - project: templates/ci
    file: docker.yml
  - project: templates/ci
    file: docker-hub.yml

################################################################################
# Workflow
workflow:
  rules:
    # If $VERSION variable defined have it take precedence over the commit tag
    - if: $VERSION
      variables:
        RELEASE: "${VERSION}"
    # When the CI_COMMIT_TAG is present we are override the Gradle command
    # and configuring the tag as the version to build
    - if: $CI_COMMIT_TAG
      variables:
        RELEASE: "${CI_COMMIT_TAG}"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never
    - if: "$CI_COMMIT_BRANCH"
    - when: always

################################################################################
# Template(s)
################################################################################
.build:
  stage: build
  interruptible: true
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  script:
    - make build push

################################################################################
# Job Configuration
################################################################################
psql:9:
  extends: .build
  variables:
    ALPINE_VERSION: "3.17"
    DOCKER_FILE: Dockerfile.9
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:9
    DOCKERHUB_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:9
  only:
    - main
    - schedules

psql:9:dockerhub:
  extends: .dockerhub
  stage: dockerhub
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:9
    DOCKERHUB_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:9
  only:
    - main
    - schedules

psql:10:
  extends: .build
  variables:
    ALPINE_VERSION: "3.17"
    DOCKER_FILE: Dockerfile.10
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:10
    DOCKERHUB_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:10
  only:
    - main
    - schedules

psql:10:dockerhub:
  extends: .dockerhub
  stage: dockerhub
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:10
    DOCKERHUB_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:10
  only:
    - main
    - schedules

psql:11:
  extends: .build
  variables:
    ALPINE_VERSION: "3.10"
    DOCKER_FILE: Dockerfile.11
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:11
    DOCKERHUB_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:11
  only:
    - main
    - schedules

psql:11:dockerhub:
  extends: .dockerhub
  stage: dockerhub
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:11
    DOCKERHUB_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:11
  only:
    - main
    - schedules

psql:12:
  extends: .build
  variables:
    ALPINE_VERSION: "3.17"
    DOCKER_FILE: Dockerfile.12
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:12
    DOCKERHUB_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:12
  only:
    - main
    - schedules

psql:12:dockerhub:
  extends: .dockerhub
  stage: dockerhub
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:12
    DOCKERHUB_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:12
  only:
    - main
    - schedules

psql:13:
  extends: .build
  variables:
    ALPINE_VERSION: "3.17"
    DOCKER_FILE: Dockerfile.13
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:13
    DOCKERHUB_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:13
  only:
    - main
    - schedules

psql:13:dockerhub:
  extends: .dockerhub
  stage: dockerhub
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:13
    DOCKERHUB_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:13
  only:
    - main
    - schedules

psql:14:
  extends: .build
  variables:
    ALPINE_VERSION: "3.17"
    DOCKER_FILE: Dockerfile.14
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:14
    DOCKERHUB_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:14
  only:
    - main
    - schedules

psql:14:dockerhub:
  extends: .dockerhub
  stage: dockerhub
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:14
    DOCKERHUB_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:14
  only:
    - main
    - schedules

psql:15:
  extends: .build
  variables:
    ALPINE_VERSION: "3.15"
    DOCKER_FILE: Dockerfile.15
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:15
    DOCKERHUB_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:15
  only:
    - main
    - schedules

psql:15:dockerhub:
  extends: .dockerhub
  stage: dockerhub
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:15
    DOCKERHUB_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:15
  only:
    - main
    - schedules

psql:latest:
  extends: .build
  stage: latest
  variables:
    ALPINE_VERSION: "3.17"
    DOCKER_FILE: Dockerfile
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
    DOCKERHUB_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest
  only:
    - main
    - schedules

psql:latest:dockerhub:
  extends: .dockerhub
  stage: dockerhub
  variables:
    DOCKERHUB_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest
  only:
    - main
    - schedules

branches:
  extends: .build
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_SLUG}
  only:
    - branches
  except:
    - main
