image: registry.timmertech.nl/docker/docker:latest

stages:
  - build
  - trigger

variables:
  CI: "true"
  DOCKER_DRIVER: overlay2

################################################################################
# Workflow
workflow:
  rules:
    # If $VERSION variable defined have it take precedence over the commit tag
    - if: $VERSION
      variables:
        RELEASE: "${VERSION}"
    # When the CI_COMMIT_TAG is present we are override the Gradle command
    # and configuring the tag as the version to build
    - if: $CI_COMMIT_TAG
      variables:
        RELEASE: "${CI_COMMIT_TAG}"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never
    - if: "$CI_COMMIT_BRANCH"
    - when: always

################################################################################
# Template(s)
################################################################################
.build:
  stage: build
  interruptible: true
  variables:
    DOCKER_FILE: Dockerfile
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  before_script:
    - echo "${CI_DEPENDENCY_PROXY_PASSWORD}" | docker login -u "${CI_DEPENDENCY_PROXY_USER}" --password-stdin "${CI_DEPENDENCY_PROXY_SERVER}"
    - echo ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - make build push

################################################################################
# Job Configuration
################################################################################
release:
  extends: .build
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_TAG}
  only:
    - tags

branches:
  extends: .build
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_SLUG}
  only:
    - branches
  except:
    - master

update:
  extends: .build
  only:
    - master
    - schedules

docker.hub:
  stage: trigger
  interruptible: true
  only:
    - tags
    - schedules
  script:
    - curl -s -H -X POST ${DOCKERHUB_TRIGGER} > /dev/null
# EOF
