default:
  interruptible: false
  image:
    name: registry.timmertech.nl/docker/docker:latest
    pull_policy: always

include:
  - project: templates/ci
    file: docker.yml

base:
  extends: .docker-build-multi
  stage: build
  only:
    - main
    - schedules
    - branches
  variables:
    PLATFORM: "linux/arm64,linux/amd64"
    DOCKER_FILE: docker/Dockerfile.base
    DOCKER_HUB: "ENABLED"
    DOCKER_IMAGE: ${DOCKER_IMAGE_PATH}:base
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:base
