version: '3.9'

networks:
  psql-playground:
    external: true

services:
  psql-master:
    image: gjrtimmer/postgresql:latest
    container_name: psql-master
    hostname: master
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
      PUID: ${PUID}
      PGID: ${PGID}
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: test
      PL_PERL: "ENABLED"
      PL_PYTHON: "ENABLED"
      PL_TCL: "ENABLED"
      PG_CRON: "ENABLED"
      REPLICATION_USER: replicator
      REPLICATION_PASS: replicator
      REPLICATION_MODE: master
      PG_JOURNAL_MAX_SENDERS: 10
    networks:
      psql-playground:
        ipv4_address: 172.50.0.10
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/data:/config
