version: '3.9'

services:
  psql-master:
    image: gjrtimmer/postgresql:latest
    container_name: psql-master
    hostname: psql
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
      PUID: ${PUID}
      PGID: ${PGID}
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: test
      PL_PERL: "ENABLED"
      PL_PYTHON: "ENABLED"
      PL_TCL: "ENABLED"
      REPLICATION_USER: replicate
      REPLICATION_PASS: replicate
      REPLICATION_MODE: master
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/data:/config
